# Generated by Django 4.1.7 on 2023-03-24 15:19

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.walletuser"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to="users.walletuser",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="tasks.TaggedTask",
                to="tasks.TaskTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="users",
            field=models.ManyToManyField(
                related_name="joined_tasks",
                through="tasks.TaskUser",
                to="users.walletuser",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="verification_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.taskclass"
            ),
        ),
        migrations.AddField(
            model_name="taggedtask",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_tagged_items",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AddField(
            model_name="taggedtask",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="tasks.tasktag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskuser",
            unique_together={("user", "task")},
        ),
    ]
