# Generated by Django 4.1.7 on 2023-03-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="verification_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="Verification Url"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="verification_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.taskclass",
            ),
        ),
    ]
