# Generated by Django 4.1.9 on 2023-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_taskuser_request_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="mode",
            field=models.IntegerField(
                choices=[(0, "Verify"), (1, "Approve")],
                db_index=True,
                default=0,
                verbose_name="Mode",
            ),
        ),
        migrations.AddField(
            model_name="taskuser",
            name="verify_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=42,
                null=True,
                verbose_name="Verify Address",
            ),
        ),
    ]
